quote="I think there is a world market for maybe five computers."
print("The quote-")
print(quote)
print("Now in UPPERCASE-")
print(quote.upper())
print("Now in lowercase-")
print(quote.lower())
print("Now all the cases of each letter will be switched-")
print(quote.swapcase())
print("Now as a Title-")
print(quote.title())
print("I will make a more accurate prediction now-")
print(quote.replace("five", "billions of"))
print("After all of that, the original quote is still here-")
print(quote)
input("\n\nPress the escape button to exit.")